apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: "redisHost"
    value: "mujredis.redis.cache.windows.net:6379"
  - name: "redisPassword"
    value: "l+91xzVZB+ZCm+yrBQxx4lm5fjdvqyS2r4aVQJ1992A="