apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: {{.Values.app.replicas}}
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: "{{.Values.app.imagename}}:{{.Values.app.imagetag}}"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: aspenv
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:80"
            - name: SQLCONNSTR_mojeDB
              valueFrom:
                secretKeyRef:
                  name: db
                  key: connectionString
          livenessProbe:
            httpGet:
              path: /api/version
              port: 80
          readinessProbe:
            httpGet:
              path: /api/version
              port: 80
          resources:
            requests:
              cpu: 100m
              memory: 128M
            limits:
              cpu: 500m
              memory: 512M
          volumeMounts:
          - name: config-volume
            mountPath: /myconfigs
      volumes:
      - name: config-volume
        configMap:
          name: web-config
