apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-pubsub-servicebus
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    value: {{ .Values.serviceBus.connectionString }}