apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-eventhub
spec:
  type: bindings.azure.eventhubs
  metadata:
  - name: connectionString
    value: {{ .Values.eventHub.connectionString }}