apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: myweb-service-policy
spec:
  destination:
    name: myweb-service
  circuitBreaker:
    simpleCb:
      httpMaxRequests: 1
      httpMaxPendingRequests: 1
      sleepWindow: 5s